main/urls.py
from django.urls import path
from . import views, models

urlpatterns=[
    path('',views.index, name='home'),
    path('login/', views.LoginUser.as_view(),name='login'),
    path('logout/', views.logout_user,name='logout'),
    path('students/',views.AllStudents.as_view(),name='students'),
    path('students/export/<format>',views.export_data,name='students_export'),
    path('students/addstudent',views.StudentCreate.as_view(), name='add_student'),
    path('students/<student_id>/update', views.UpdateStudent.as_view(), name='update_student'),
    path('student/<student_id>/add_discipline/', views.AddCompletedDiscipline.as_view(), name='add_completed_discipline'),
    path('students/<student_id>/delete', views.DeleteStudent.as_view(), name='delete_student'),
    path('students/<student_id>',views.OneStudent.as_view(), name='student'),
    path('groups/',views.AllGroups.as_view(), name='groups'),
    path('groups/add_group',views.GroupCreate.as_view(), name='add_group'),
    path('discipline_add/', views.DisciplineCreate.as_view(), name='add_discipline'),
    path('groups/<group_id>',views.OneGroup.as_view(), name='group'),
    path('teachers/',views.AllTeachers.as_view(),name='teachers'),
    path('teachers/addteacher',views.TeacherCreate.as_view(), name='add_teacher'),
    path('teachers/<teacher_id>',views.OneTeacher.as_view(), name='teacher'),
    path('teachers/<teacher_id>/delete', views.DeleteTeacher.as_view(), name='delete_teacher'),
]

strec/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('record', include('record.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models
from django.urls import reverse, reverse_lazy
from django.contrib.auth.models import User
from random import randint
import datetime
class Teacher(models.Model):
    name = models.CharField('ФИО преподавателя', max_length=100) #varchar(100) NOT NULLL
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('teacher',kwargs={'teacher_id':self.id})
    def delete(self):
        self.user.delete() 
        return reverse('home')
    class Meta:
        verbose_name = 'Преподаватель'
        verbose_name_plural = 'Преподаватели'
class Syllabus(models.Model):
    course = models.IntegerField('Расписание на курс', default=1)
    set_date = models.DateField('Дата утверждения', default=datetime.date.today())
    discipline=models.ManyToManyField('Discipline')
    class Meta:
        verbose_name = 'Расписание'
        verbose_name_plural = 'Расписания'
class Group(models.Model):
    name = models.CharField('Название группы', max_length=100, unique=True) #varchar(100) not null unique
    syllabus = models.ManyToManyField('Syllabus') #references syllabus
    course = models.IntegerField('Номер курса',default=1)#int not null default(1)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'Группа'
        verbose_name_plural = 'Группы'
    def get_absolute_url(self):
        return reverse_lazy('groups')
class Student(models.Model):
    name = models.CharField('ФИО студента', max_length=100) #varchar(100) not null
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    group = models.ForeignKey('Group', on_delete=models.CASCADE) #references study_group
    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('students')
    def delete(self):
        self.user.delete() 
        return reverse('home')
    class Meta:
        verbose_name = 'Студент'
        verbose_name_plural = 'Студенты'
class RecordBook(models.Model):
    number = models.PositiveBigIntegerField('Номер зачетной книжки')
    student = models.OneToOneField('Student', on_delete=models.CASCADE, primary_key=True) #references student
    completed_disciplines=models.ManyToManyField('CompletedDisciplines')
    class Meta:
        verbose_name = 'Зачетная книжка'
        verbose_name_plural = 'Зачетные книжки'
class Discipline(models.Model):
    name = models.CharField('Название дисциплины', max_length=100) #varchar(100) not null
    teacher=models.ManyToManyField('Teacher')
    type_of_assesment=models.CharField('Вид оценивания', max_length=50, default='Зачет')
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'Дисциплина'
        verbose_name_plural = 'Дисциплины'
    def get_absolute_url(self):
        return reverse_lazy('home')
class CompletedDisciplines(models.Model):
    hours = models.IntegerField('Количество часов', default=100)#int not null
    mark = models.CharField('Оценка', max_length=10, default='Зачет')
    discipline = models.ForeignKey('Discipline', on_delete=models.CASCADE) #references discipline
    class Meta:
        verbose_name = 'Завершенная дисциплина'
        verbose_name_plural = 'Завершенные дисциплины'

main/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User, Group as AGroup

from .models import Teacher, Student, RecordBook, Discipline, CompletedDisciplines, Group, Syllabus
from random import randint
class StudentForm(forms.ModelForm):
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    class Meta:
        model = Student
        fields = ['name', 'group', 'password']
    def save(self, commit=True):
        student = super().save(commit=False)
        student.user = User.objects.create_user(
            username=f'student_{student.name}',
            password=self.cleaned_data['password'])
        if commit:
            student.save()
            student_group, created= AGroup.objects.get_or_create(name='students group')
            student.user.groups.add(student_group)
        return student
class UpdateStudentForm(forms.ModelForm):
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    class Meta:
        model = Student
        fields = ['name']
class TeacherForm(forms.ModelForm):
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    class Meta:
        model = Teacher
        fields = ['name']
    def save(self, commit=True):
        teacher = super().save(commit=False)
        teacher.user = User.objects.create_user(
            username=f'teacher_{teacher.name}',
            password=self.cleaned_data['password'])
        if commit:
            teacher.save()
            teacher_group, created= AGroup.objects.get_or_create(name='teacher group')
            teacher.user.groups.add(teacher_group)
        return teacher
class RecordBookForm(forms.ModelForm):
    class Meta:
        model = RecordBook
        fields = ['number']
class DisciplineForm(forms.ModelForm):
    types = ['Зачет', 'Диф. Зачет', 'Экзамен', 'Практика']
    type_of_assesment = forms.ChoiceField(choices=[(type, type) for type in types])
    class Meta:
        model = Discipline
        fields = '__all__'
class SyllbusForm(forms.ModelForm):
    class Meta:
        model = Syllabus
        fields = '__all__'
class GroupForm(forms.ModelForm):
    class Meta:
        model = Group
        fields = '__all__'
class CompletedDisciplinesForm(forms.ModelForm):
    CHOICES = [('Зачет', 'Зачет')] + [(str(mark), str(mark)) for mark in range(3, 6)]
    mark = forms.ChoiceField(choices=CHOICES, required=True)
    class Meta:
        model = CompletedDisciplines
        fields = '__all__'
    def clean(self):
        cleaned_data = super().clean()
        discipline = cleaned_data.get('discipline')
        mark = cleaned_data.get('mark')
        if discipline.type_of_assesment in ['Диф. Зачет', 'Экзамен', 'Практика'] and mark == 'Зачет'  or discipline.type_of_assesment == 'Зачет' and mark != 'Зачет':
            raise forms.ValidationError('Неверная оценка для данного типа оценивания')
        return cleaned_data
class LoginUserForm(AuthenticationForm):
    username=forms.CharField(label='Login',widget=forms.TextInput(attrs={'class':'form-input'}))
    password=forms.CharField(label='Password',widget=forms.PasswordInput(attrs={'class':'form-input'}))

main/views.py
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.http import HttpResponse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Teacher, Group, Student, Discipline, CompletedDisciplines, Syllabus
from .forms import LoginUserForm, RecordBookForm, StudentForm,DisciplineForm, CompletedDisciplinesForm, TeacherForm, GroupForm, SyllbusForm, UpdateStudentForm
from .resources import StudentResource
class TeacherRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.groups.filter(name='teacher group').exists() or self.request.user.is_superuser
class StudentRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.user.groups.filter(name='students group').exists() or self.request.user.is_superuser
class AdminRequiredMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user.is_superuser
def index(request):
    data={
        'title':'main page'
    }
    return render(request, 'main/index.html', data)
class LoginUser(LoginView):
    form_class=LoginUserForm
    template_name='main/login.html'
    def get_success_url(self):
        return reverse_lazy('home')
def logout_user(request):
    logout(request)
    return redirect('home')
class AllTeachers(LoginRequiredMixin,ListView):
    model=Teacher
    template_name='main/teachers.html'
    context_object_name='teachers'
    extra_context={
        'title':'teachers page',
        'content':'teachers'
        }
    login_url='login'
class TeacherCreate(AdminRequiredMixin,CreateView):
    model=Teacher
    form_class = TeacherForm
    template_name = 'main/add.html' 
class OneTeacher(LoginRequiredMixin,DetailView):
    model=Teacher
    template_name='main/teacher.html'
    pk_url_kwarg='teacher_id'
    context_object_name='teacher'
    login_url='login'
class AllStudents(LoginRequiredMixin,ListView):
    model=Student
    template_name='main/students.html'
    context_object_name='students'
    extra_context={
        'title':'students page',
        'content':'students'
        }
    login_url='login'
class OneStudent(LoginRequiredMixin,DetailView):
    model=Student
    template_name='main/student.html'
    pk_url_kwarg='student_id'
    context_object_name='student'
    def get(self, request, *args, **kwargs):
        student_id = self.kwargs.get(self.pk_url_kwarg)
        student = Student.objects.get(pk=student_id)
        if request.user == student.user or request.user.groups.filter(name='teacher group').exists() or request.user.is_superuser:
            return super().get(request, *args, **kwargs)
        else:
            return redirect('home')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        student_id = self.kwargs.get('student_id')
        student = Student.objects.get(pk=student_id)
        syllabus_disciplines = Discipline.objects.filter(
            syllabus__group=student.group
        )
        completed_disciplines = Discipline.objects.filter(
            completeddisciplines__recordbook__student=student,
        )
        debts = syllabus_disciplines.exclude(
            pk__in=completed_disciplines.values_list('pk', flat=True)
        )
        context['debts'] = debts
        return context
    login_url='login'
class StudentCreate(AdminRequiredMixin,CreateView):
    model = Student
    form_class = StudentForm
    template_name = 'main/addstudent.html'
    success_url = reverse_lazy('students') 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'recordbook_form' not in context:
            context['recordbook_form'] = RecordBookForm()
        return context
    def form_valid(self, form):
        self.object = form.save()
        recordbook_form = RecordBookForm(self.request.POST)
        if recordbook_form.is_valid():
            record_book = recordbook_form.save(commit=False)
            record_book.student = self.object
            record_book.save()
        return redirect(self.get_success_url())
    def post(self, request, *args, **kwargs):
        self.object = None
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        recordbook_form = RecordBookForm(request.POST)
        if form.is_valid() and recordbook_form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
    def form_invalid(self, form):
        recordbook_form = RecordBookForm(self.request.POST)
        return self.render_to_response(self.get_context_data(form=form, recordbook_form=recordbook_form))
    redirect_field_name='home'
class DisciplineCreate(AdminRequiredMixin,CreateView):
    model=Discipline
    form_class = DisciplineForm
    template_name = 'main/add.html' 
class AddCompletedDiscipline(TeacherRequiredMixin, CreateView):
    model = CompletedDisciplines
    form_class = CompletedDisciplinesForm
    template_name = 'main/add.html'
    def form_valid(self, form):
        student = Student.objects.get(pk=self.kwargs['student_id'])
        discipline_to_add = form.cleaned_data['discipline']
        syllabuses = Syllabus.objects.filter(group=student.group)
        if not syllabuses.filter(course__lte=student.group.course, discipline=discipline_to_add).exists():
            form.add_error('discipline', 'Дисциплина не соответствует расписанию и курсу студента.')
            return self.form_invalid(form)
        self.object = form.save()
        student.recordbook.completed_disciplines.add(self.object)
        return super().form_valid(form)
    def get_success_url(self):
        return reverse_lazy('students')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['student'] = Student.objects.get(pk=self.kwargs['student_id'])
        return context
class UpdateStudent(AdminRequiredMixin,UpdateView):
    model=Student
    form_class=UpdateStudentForm
    template_name='main/add.html'
    pk_url_kwarg='student_id'
class DeleteStudent(AdminRequiredMixin,DeleteView):
    model=Student
    template_name='main/delete.html'
    pk_url_kwarg='student_id'
    success_url=reverse_lazy('students')
class DeleteTeacher(AdminRequiredMixin,DeleteView):
    model=Teacher
    template_name='main/delete.html'
    pk_url_kwarg='teacher_id'
    success_url=reverse_lazy('teachers')
class AllGroups(LoginRequiredMixin,ListView):
    model=Group
    template_name='main/groups.html'
    context_object_name='groups'
    extra_context={
        'title':'groups page',
        'content':'groups'
        }
    login_url='login'
class OneGroup(LoginRequiredMixin,DetailView):
    model=Group
    template_name='main/group.html'
    pk_url_kwarg='group_id'
    context_object_name='group'
    login_url='login'
class GroupCreate(AdminRequiredMixin,CreateView):
    model=Group
    form_class = GroupForm
    template_name = 'main/add.html' 
class SyllbusCreate(AdminRequiredMixin,CreateView):
    model=Syllabus
    form_class = SyllbusForm
    template_name = 'main/add.html' 
def export_data(request, format):
    student_resource = StudentResource()
    dataset = student_resource.export()
    if format=='CSV':
        response = HttpResponse(dataset.csv, content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename="exported_data.csv"'
        return response
    elif format=='JSON':
        response = HttpResponse(dataset.json, content_type='application/json')
        response['Content-Disposition'] = 'attachment; filename="exported_data.json"'
        return response

main/templates/main/add.html
{% extends 'main/layout.html' %}

{% block title %} add  {% endblock %}
{% block content %} 
<div class="features">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="button">Add </button>
    </form>
</div>
{% endblock %} 

main/templates/main/addstudent.html
{% extends 'main/layout.html' %}

{% block title %} add student {% endblock %}
{% block content %} 
<div class="features">
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {{ recordbook_form.as_p }}
        <button type="sumbit" class="button">Add student</button>
    </form>
</div>
{% endblock %} 

main/templates/main/delete.html
{% extends 'main/layout.html' %}

{% block title %} delete {% endblock %}
{% block content %} 
<div class="features">
    <form method="post">
        {% csrf_token %}
        <button type="sumbit" class="index-button">Delete</button>
<div>
{% endblock %} 

main/templates/main/group.html
{% extends 'main/layout.html' %}

{% block title %} {{ group.name }} {% endblock %}
{% block content %} 
<div class="features">
    <h1>group:{{ group.name }}, course:{{ group.course }}</h1>
    <table>
        <tr>students:</tr>
        <tr>
            <td>name</td>
        </tr>
        {% for student in group.student_set.all %}
        <tr>
            <td><a href="{% url 'student' student.id %}">{{student.name}}</a></td>
        </tr>
        {% endfor %}
    </table>
    <table>
        <tr>syllabus:</tr>
        <tr>
            <td>name of discipline</td>
            <td>type of assesment</td>
            <td>course</td>
        </tr>
        {% for syllabuses in group.syllabus.all %}
        {% for discipline in syllabuses.discipline.all %}
        <tr>
            <td>
                <div>{{discipline}}</div>
            </td>
            <td>
                <div>{{discipline.type_of_assesment}}</div>
            </td>
            <td>{{syllabuses.course}}</td>
        </tr>
        {% endfor %}
        {% endfor %}
    </table>
</div>

{% endblock %}

main/templates/main/groups.html
{% extends 'main/layout.html' %}

{% block title %} {{ title }} {% endblock %}
{% block content %} 
<div class="features">
    <h1>{{ content }}</h1>
    <table class="table">
        <thead>
            <tr>
                <th>group name</td>
                <th>course</td>
            </tr>
        </thead>
        <tbody>
            {% for group in groups %}
            <tr>
                <td><a href="{% url 'group' group.id %}">{{group.name}}</a></td>
                <td>{{group.course}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {%if user.is_superuser%}
    <form action="{% url 'add_group' %}">
        <button type="submit" class="button">Add group</button>
    </form>
    <form action="{% url 'add_discipline' %}">
        <button type="submit" class="button">Add discipline</button>
    </form>
    {%endif%}
</div>

{% endblock %}

main/templates/main/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Home page</title>
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
    <main>
        {% if request.user.is_authenticated %}
        <p align="right">Welcome, {{ request.user.get_username }}</p>
        <form action="{% url 'logout' %}">
            <button type="submit" class="button">logout</button>
        </form>
        {% else %}
        <form action="{% url 'login' %}">
            <button type="submit" class="button">login</button>
        </form>
        {% endif %}
        <div class="features">
          <h1>Welcome to student record site</h1>
          <form action="{% url 'students' %}">
            <button type="submit" class="index-button">students</button>
          </form>
          <form action="{% url 'groups' %}">
            <button type="submit" class="index-button">groups</button>
          </form>
          <form action="{% url 'teachers' %}">
          <button type="submit" class="index-button">teachers</button>
          </form>
        </div>
        {% block content %}{% endblock %}
    </main>
</body>
</html>

main/templates/main/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
    <aside>
        <img src="{%static 'main/img/university.svg'%}"alt='logo'>
        <ul>
            <a href="{% url 'home' %}"><li><img src="{%static 'main/img/home.svg'%}"alt='home'>home</li></a>
            <a href="{% url 'students' %}"><li><img src="{%static 'main/img/student.svg'%}"alt='student'>students</li></a>
            <a href="{% url 'groups' %}"><li><img src="{%static 'main/img/groups.svg'%}"alt='groups'>groups</li></a>
            <a href="{% url 'teachers' %}"><li><img src="{%static 'main/img/teacher.svg'%}"alt='teacher'>teachers</li></a>
        </ul>
    </aside>
    <main>
        {% if request.user.is_authenticated %}
        <p align="right">Welcome, {{ request.user.get_username }}</p>
        <form action="{% url 'logout' %}">
            <button type="submit" class="button">logout</button>
        </form>
        {% else %}
        <form action="{% url 'login' %}">
            <button type="submit" class="button">login</button>
        </form>
        {% endif %}
        {% block content %}{% endblock %}
    </main>
</body>
</html>

main/templates/main/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
    <main>
      <div class="features">
        <form method="post">
          {% csrf_token %}
          <div class="form-error">{{form.non_field_errors}}</div>
          {% for f in form %}
          <p><label class="form-label" for="{{f.id_for_label}}">{{f.label}}:</label>{{f}}</p>
          <div class = "form-error">{{f.errors}}</div>
          {% endfor %}
          <button type="submit" class="button">Login</button>
        </form>
      </div>
    </main>
</body>
</html>

main/templates/main/student.html
{% extends 'main/layout.html' %}
{% block title %} {{ student.name }} {% endblock %}
{% block content %} 
<div class="features">
    <h1>{{ student.name }}, <a href="{% url 'group' student.group.id %}">{{student.group.name}}</a>, course: {{student.group.course}}</h1>
    <p>record book №{{student.recordbook.number}}</p>
    <table class="table">
        <thead>
        <tr>
            <th>name of discipline</th>
            <th>mark</th>
        </tr>
        </thead>
        <tbody>
        {% for completed_discipline in student.recordbook.completed_disciplines.all %}
        <tr>
            <td>{{completed_discipline.discipline.name}}</td>
            <td>{{completed_discipline.mark}}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <p>academic debt</p>
    <table class="table">
        <thead>
        <tr>
            <th>name of discipline</th>
            <th>type of assesment</th>
            <th>course</th>
        </tr>
        </thead>
        <tbody>
        {% for syllabuses in student.group.syllabus.all %}
        {% if syllabuses.course <= student.group.course %}
        {% for debt in debts %}
        <tr>
            {% if debt in syllabuses.discipline.all %}
            <td>
                <div>{{debt.name}}</div>
            </td>
            <td>
                <div>{{debt.type_of_assesment}}</div>
            </td>
            <td>{{syllabuses.course}}</td>
            {% endif %}
        </tr>
        {% endfor %}
        {% endif %}
        {% endfor %}
        </tbody>
    </table>
    {%if user.is_superuser%}
    <form action="{% url 'delete_student' student.id %}">
        <button type="submit" class="button">delete student</button>
    </form>
    <form action="{% url 'update_student' student.id %}">
        <button type="submit" class="button">update student</button>
    </form>
    {%endif%}
    {%if user.groups.last.name == 'teacher group' or user.is_superuser%}
    <form action="{% url 'add_completed_discipline' student.id %}">
        <button type="submit" class="button">add completed discipline</button>
    </form>
    {%endif%}
</div>
{% endblock %}

main/templates/main/students.html
{% extends 'main/layout.html' %}

{% block title %} {{ title }} {% endblock %}
{% block content %} 
<div class="features">
    <h1>{{ content }}</h1>
    <table class="table">
        <thead>
            <tr>
                <th>name</th>
                <th>group</th>
                <th>course</th>
            </tr>
        </thead>
        <tbody>
            {% for student in students %}
            <tr>
                <td><a href="{% url 'student' student.id %}">{{student.name}}</a></td>
                <td><a href="{% url 'group' student.group.id %}">{{student.group}}</a></td>
                <td>{{student.group.course}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {%if user.is_superuser%}
    <form action="{% url 'add_student' %}">
        <button type="submit" class="button">Add student</button>
    </form>
    <a href="{% url 'students_export' format='CSV' %}">CSV</a>
    <a href="{% url 'students_export' format='JSON' %}">JSON</a>
    {%endif%}
</div>

{% endblock %}

main/templates/main/teacher.html
{% extends 'main/layout.html' %}

{% block title %} teachers {% endblock %}
{% block content %} 
<div class="features">
   <p>{{teacher.name}}</p>
</div>
{%if user.is_superuser%}
<form action="{% url 'delete_teacher' teacher.id %}">
    <button type="submit" class="button">delete teacher</button>
</form>
{%endif%}

{% endblock %}

main/templates/main/teachers.html
{% extends 'main/layout.html' %}

{% block title %} teachers {% endblock %}
{% block content %} 
<div class="features">
    <table class="table">
        <thead>
            <tr>
                <th>teacher name</td>
            </tr>
        </thead>
        <tbody>
            {% for teacher in teachers %}
            <tr>
                <td><a href="{% url 'teacher' teacher.id %}">{{teacher.name}}</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    {%if user.is_superuser%}
    <form action="{% url 'add_teacher' %}">
        <button type="submit" class="button">Add teacher</button>
    </form>
    <form action="{% url 'add_discipline' %}">
        <button type="submit" class="button">Add discipline</button>
    </form>
    {%endif%}
</div>

{% endblock %}